### ISSUE TITLE
[경험 분해] 키워드 관련 ISSUE

### ISSUE THREAD

**Issue by PracticeEveryday** [depromeet/13th-4team-backend#107]
# 경험 분해 관련 데이터베이스 스키마 질문드립니다.

### 경험 분해 키워드 전제 조건
1. 하나의 경험 분해 카드는 여러 개의 키워드를 가진다.
2. 하나의 키워드는 여러개의 경험 분해 카드를 가진다.
3. 하나의 유저는 여러 개의 키워드를 가진다.

### 현재 DB Schema
- capability
<img width="560" alt="image" src="https://github.com/depromeet/13th-4team-backend/assets/97580759/644e758a-e833-4ff9-9790-50dc72013469">
- experience_capability
<img width="380" alt="image" src="https://github.com/depromeet/13th-4team-backend/assets/97580759/de52f064-08e9-4c74-9bd2-27b07b32c266">

- 지금과 같은 스키마에서 experience_capability는 experience n:m capability 정보를 담기위한 데이터베이스입니다.
- 하지만 capability 데이터베이스가 userId를 가지고 있게 되는데 이는 capability 1:n user 의 관계를 갖게 되므로 capability가 유저가 가지는 키워드 만큼 쌓이게 됩니다.
- 그럼 experience_capability에서 capability는 고정되지 않고 계속해서 id 값이 늘어나게 될 텐데 이런 부분은 어떻게 스키마를 수정하면 좋을까요?
---

- 저는 capability와 userId 사이의 n:m 관계를 하나 더 두어서 관리하는 것을 생각 했습니다.

즉
1. 하나의 경험 분해 카드는 여러 개의 키워드를 가진다.
2. 하나의 키워드는 여러개의 경험 분해 카드를 가진다.
3. 하나의 유저는 여러 개의 키워드를 가진다.
여기에 4가 추가되는 것입니다.
4. 하나의 키워드는 여러개의 유저를 가진다.

**Comment by PracticeEveryday** [comment]
+ 그리고 해당 부분에에서 키워드를 클릭하면 하나 씩 추가하는 API를 만드는 것이 좋을까요 아니면 클릭 한 후 keyword를 전부 받아 한 번에 만드는 방법이 더 나을까요?
<img width="388" alt="image" src="https://github.com/depromeet/13th-4team-backend/assets/97580759/f2ecf9bb-c95c-423d-a895-d4ed840823c4">

**Comment by PracticeEveryday** [comment]
+... 요부분은 데이터베이스 스키마 구성하실 때 어떤 역할을 기대하고 나누신 것도 궁금합니다 ㅎ.ㅎㅎㅎㅎ

<img width="596" alt="image" src="https://github.com/depromeet/13th-4team-backend/assets/97580759/dcc975ac-7fbc-4095-9877-bfc68e1a5e87">

**Comment by stae1102** [comment]
> * 지금과 같은 스키마에서 experience_capability는 experience n:m capability 정보를 담기위한 데이터베이스입니다.
> * 하지만 capability 데이터베이스가 userId를 가지고 있게 되는데 이는 capability 1:n user 의 관계를 갖게 되므로 capability가 유저가 가지는 키워드 만큼 쌓이게 됩니다.
> * 그럼 experience_capability에서 capability는 고정되지 않고 계속해서 id 값이 늘어나게 될 텐데 이런 부분은 어떻게 스키마를 수정하면 좋을까요?
> 
> * 저는 capability와 userId 사이의 n:m 관계를 하나 더 두어서 관리하는 것을 생각 했습니다.
> 
> 즉
> 
> 1. 하나의 경험 분해 카드는 여러 개의 키워드를 가진다.
> 2. 하나의 키워드는 여러개의 경험 분해 카드를 가진다.
> 3. 하나의 유저는 여러 개의 키워드를 가진다.
>    여기에 4가 추가되는 것입니다.
> 4. 하나의 키워드는 여러개의 유저를 가진다.

오 동현님 정리감사합니다. 저도 이 부분에 대해서 고민이 조금 됐었는데요, experience_id와 capability_id를 experience_capability에서 합성키로 사용하고 있는 상황입니다. 그래서, experience와 capability가 모두 존재해야지 experience_capability 테이블에 값이 생기는 거죠!

> * 그럼 experience_capability에서 capability는 고정되지 않고 계속해서 id 값이 늘어나게 될 텐데 이런 부분은 어떻게 스키마를 수정하면 좋을까요?

그리고 capability 테이블에서 row 개수가 증가하더라도 experience_capability에서 row를 생성하지 않으면 되어서 capability의 row 개수가 늘어나든 줄어들든 영향을 미치지 않을 것으로 보입니다.

여기서 capability의 id는 1, 2, 3으로 증가하며 experience_capability의 테이블에서 capability_id가 1, 2, 3으로 쌓이는데 experience_id는 1로 고정되어 있는 경우를 가정했을 때 experience 값이 고정되어 중복이 발생하기 때문에 고민이 되시는 것이죠?? 이 부분은 experience_capability의 experience_id와 capability_id의 컬럼 속성이 unique가 아닌 것으로 알고 있어서 이 부분도 괜찮을 거예요! 합성키라서 둘 다 중복되는 케이스를 제외하고는 고유한 키로 간주할 수 있기 때문입니다.

예를 들어, `capability_id = 1, experience_id = 1`, `capability_id = 2,  experience_id = 1`, `capability_id = 3,  experience_id = 1` 는 experience_id가 중복된다고 하더라도 capability_id가 다르기 때문에 키를 합성하여 봤을 때는 서로 다른 키로 간주되는 것이죠!! 물론 두 개의 `capability_id = 1, experience_id = 1`가 입력으로 들어온다면 둘은 합성을 해도 같은 키이기 때문에 unique contraint에 걸리게 되겠죠??

**Comment by stae1102** [comment]
> * 저는 capability와 userId 사이의 n:m 관계를 하나 더 두어서 관리하는 것을 생각 했습니다.

하나의 키워드가 여러 개의 유저를 가질 수 있다는 게 제가 확실하게 이해가 되지 않는데 혹시 추가적으로 설명을 부탁드려도 괜찮을까요? 일단 capability 테이블과 userId 테이블이 서로 n:m이라면 어떨까 하는 생각이시죠~~??

말씀해주신 것처럼 한 개의 키워드를 여러 명의 유저가 쓸 수 있고, 그렇기 때문에 한 개의 키워드에서 여러 명의 유저를 조회할 수 있다는 게 반증이 되게 되겠네요. 그렇다면, 그 키워드를 사용하는 유저를 모두 불러오는 기능이 현재 기획에 있는 것일까요?? 만약 그렇다면 n:m으로 두는 게 좋습니다. 만약 그렇지 않다면 지금 테이블 그대로 두는 것이 좋습니다!

제가 이쪽 스키마에 대해서 온전히 고려해보지 않아서 오류가 있을 수도 있습니다. 혹시 개발하시다가 오류 발생하면 말씀해 주세요!!

**Comment by stae1102** [comment]
> * 그리고 해당 부분에에서 키워드를 클릭하면 하나 씩 추가하는 API를 만드는 것이 좋을까요 아니면 클릭 한 후 keyword를 전부 받아 한 번에 만드는 방법이 더 나을까요?
> 
> <img alt="image" width="388" src="https://user-images.githubusercontent.com/97580759/243141503-f2ecf9bb-c95c-423d-a895-d4ed840823c4.png">

음... 저는 한 번에 처리하는 방법이 좋아요.

그렇게 생각한 이유는 세 가지가 있는데, 첫 번째는 API 요청으로 인해 딜레이가 되기 때문이었습니다. 한 개의 키워드를 클릭해 API 요청이 보내지면 물론 응답 시간이 짧다고 하더라도 일단 딜레이가 생길 수 있다는 것은 절대적이기 때문에 유저 경험이 좋지 않을 수 있다고 생각했어요.

두 번째는 화면이 넘어가면서 딜레이를 감출 수 있다고 생각했기 때문입니다. 화면을 넘어가면서 전환될 때 자연스레 API 요청을 보내면 API 응답 시간 동안 전환이 발생하므로 자연스럽게 흘려보낼 수 있어 보입니다.

세 번째는 프론트에서 유효성 검사 방식이나 요청 보내는 방식이 간단해지고, 컴포넌트별로 API 요청을 달아줄 필요가 없다는 점이 좋다고 생각했기 때문입니다. 모든 키워드 컴포넌트별로 API 요청을 보내고자 한다면, 그 컴포넌트는 약간의 종속성이 발생할 수 있어서 추상화하면 좋아보였어요.

이건 제 생각이니까 동현님께서 잘 선택하고 구현하시길 부탁드리겠습니다 후후

**Comment by stae1102** [comment]
> +... 요부분은 데이터베이스 스키마 구성하실 때 어떤 역할을 기대하고 나누신 것도 궁금합니다 ㅎ.ㅎㅎㅎㅎ
> 
> <img alt="image" width="596" src="https://user-images.githubusercontent.com/97580759/243141528-dcc975ac-7fbc-4095-9877-bfc68e1a5e87.png">

<img width="748" alt="image" src="https://github.com/depromeet/13th-4team-backend/assets/83271772/7f851ee5-5223-4079-83db-7135aeb4c437">

요렇게 나눠서 생각하시면 되겠습니다! 배열을 넣게 되면 정규화가 되지 않아서 조회할 때 어려움이 있을 거라고 생각해서 experience_summary 테이블을 분리하는 방향을 생각했어요

**Comment by PracticeEveryday** [comment]
ㅎㅎㅎㅎ 네네 감사합니다:)
저는 고정된 키워드는 다시 생성되지 않고 n:m 테이블 개수만 증가 시키는 방식으로 생각했는데 capability에 바로바로 쌓을 수 있으면 더 어렵지 않게 구현할 수 있을 거 같습니다!

그럼 아래와 같이 중복된 부분은 추가할 수 없어요를 보여주기 위해선 프론트가 처리하게 하면 좋을까요?
그리고 고정된 키워드들은 저희가 const로 관리해서 API로 내려주는 방법을 선택해야 겠군요.
<img width="922" alt="image" src="https://github.com/depromeet/13th-4team-backend/assets/97580759/e7999b8c-191d-4d02-a9ed-7f139b74e0be">

**Comment by stae1102** [comment]
> 그럼 아래와 같이 중복된 부분은 추가할 수 없어요를 보여주기 위해선 프론트가 처리하게 하면 좋을까요?

추가하기 버튼을 눌러서 역량을 추가할 때 중복 검사를 하는 것은 어떨까요?? 아마 프론트분들께서도 검사해주실 것 같은데, 서버로 요청이 이상하게 들어오는 경우가 있을 수 있어서요~

> 그리고 고정된 키워드들은 저희가 const로 관리해서 API로 내려주는 방법을 선택해야 겠군요.

기본적으로

리더십, 협상, 설득력, 커뮤니케이션, 팀워크, 도전력, 목표달성, 추진력, 문제해결력, 실행력, 분석력, 전략적사고, 창의력, 책임감, 적극성, 성실성, 자기계발

이렇게 17개 역량 키워드가 회원가입 시에 기초로 생성됩니다!

**Comment by PracticeEveryday** [comment]
## 정리
1. 회원 가입 시에 capability에 17개의 고정된 keyword가 쌓이게 된다.

- 관련된 API는 2개입니다.
1. 새로운 키워드 추가하기 API 17개 이외의 추가되는 키워드 생성 capability에 추가됨.
2. 임시저장 클릭 시 추가 API 선택 시 capability_experience 테이블에 최대 4개의 로우 생성

**Comment by stae1102** [comment]
맞습니다!1! 정리하시느라 고생하셨어요 동현님~

**Comment by PracticeEveryday** [comment]
> 맞습니다!1! 정리하시느라 고생하셨어요 동현님~

감사합니다 :) 달려보겠습니다.!!!
