### ISSUE TITLE
[Common] 온보딩 여부 조회 API

### ISSUE THREAD

**Issue by stae1102** [depromeet/13th-4team-backend#108]
# 문제 상황

![image](https://github.com/depromeet/13th-4team-backend/assets/83271772/4cd57f0d-c741-480f-b828-3f882801e9b8)

어제 동현님께서 구두로 들으셨지만, 한 번 더 설명 드릴게요.

현재 화면마다 온보딩 페이지나 툴팁들이 존재하는데요, 이것들을 조건적으로 보여줘야 하는 상황입니다.
초기에는 DB에서 데이터가 없을 시에 경험분해에서 온보딩을 진행하는 것으로 고려하여 다른 도메인에도 그러한 GET으로 판단하는 로직을 적용하고자 했습니다.
하지만, 자기소개서는 회원가입 시에 샘플로 한 개가 생성이 되며, 나머지 툴팁들도 어떠한 조건이 있다기 보다는 처음 그 페이지를 방문한 사람인 경우에만 보여줍니다.

즉, 온보딩을 했는지 안 했는지 여부 파악을 DB와 프론트가 allignment를 맞춰야 하는 상황이 도래했습니다.
이를 위해서 위의 flow chart처럼 프론트에서 처리가 될 예정이에요.

회원가입/로그인 시, 로컬 스토리지나 리액트 쿼리 등의 전역 상태 관리 도구로 온보딩 여부에 대한 값을 가지고 있는데, 만약 이것이 유실됐을 경우 온보딩 여부를 파악할 수 없으므로, 서버에 온보딩 여부를 조회하는 API 요청을 보내 응답을 받습니다. 그후에 전역 상태 관리 툴에서 온보딩 여부를 확인하여 온보딩 진행 여부가 false(온보딩 하지 않음)의 경우에 온보딩 페이지 및 툴팁을 보여주고 서버로 온보딩 확인 사항을 업데이트 하기 위해 온보딩 업데이트 API 요청을 보냅니다. 업데이트 후 받은 온보딩 여부를 다시 로컬스토리지나 리액트 쿼리 같은 툴에 저장합니다.

만약 온보딩 진행 여부가 true인 경우에 온보딩 페이지나 툴팁을 보여주지 않아 서버로 API 요청을 별도로 보내지 않습니다.

@PracticeEveryday

**Comment by PracticeEveryday** [comment]
- 프론트 백이 모두 관리하는 것이 군요!
- 프론트에서 봤다는 것을 관리하고 API를 통해 업데이트 한다는 느낌 너무 좋습니다 😄

**Comment by stae1102** [comment]
나중에 조금 더 상세하게 설명 드리겠습니다 동현님~~!!
