### ISSUE TITLE
[경험 분해] 키워드 가져오기 API 생성

### ISSUE THREAD

**Issue by PracticeEveryday** [depromeet/13th-4team-backend#113]
- 해당 페이지 데이터를 뿌릴 때 API로 가져가기로 하였습니다.
<img width="489" alt="image" src="https://github.com/depromeet/13th-4team-backend/assets/97580759/40590171-349f-45a6-9dd3-abe7156a647d">

```
{
	‘something': true
	‘something': false
	‘something': false
	‘something': true
	‘something': true
}
```

1. Get API => true / false로 선택한 거 유무 파악하기
2. 추가하기 => 성공 시 => 17개 일 때 추가? -> 성공 된 것 포함해서(18개 return으로 돌려주기)

**Comment by stae1102** [comment]
복잡하구먼요

**Comment by PracticeEveryday** [comment]
> 복잡하구먼요

ㅎㅎㅎㅎㅎㅎ 다 하실 수 있으시면서
