### ISSUE TITLE
CI/CD

### ISSUE THREAD

**Issue by PracticeEveryday** [depromeet/13th-4team-backend#2]
# GitHub Actions + CodePipeline
- 현재 테스트 브랜치로 Push를 하면 깃헙 액션이 돌고 ECR에 latest 태그로 새로 이미지가 생성됩니다.
- 하지만 latest가 생성 된 후 또 다시 새로 푸시를 latest 태그로 이미지를 올리면 이전의 최신 이미지는 untagged로 변경됩니다.

<img width="645" alt="image" src="https://github.com/depromeet/13th-4team-backend/assets/97580759/168e4511-5268-406c-8d57-fb49542d8c8b">

---
- 이 후 latest를 바라보고 있는 CodePipeline이 재실행되고 배포가 돌게 됩니다.
- CodePipeline을 생성할 때 고정된 ECR의 태그를 하나 걸어놓아야 합니다.

<img width="941" alt="image" src="https://github.com/depromeet/13th-4team-backend/assets/97580759/b6af6f4e-1041-4529-adef-1dc3ca6e1937">

- 안 하면 latest가 default가 됩니다.
<img width="551" alt="image" src="https://github.com/depromeet/13th-4team-backend/assets/97580759/64f7c806-34e9-441d-8638-f230347d3ea0">

---
- 그렇기에 GitHub Action 스크립트에서 ECR로 태그는 유일한 hash 값으로 주는 것이 아닌 고정을 해 놓아야 합니다.
<img width="479" alt="image" src="https://github.com/depromeet/13th-4team-backend/assets/97580759/524f86e3-1321-46b6-968a-5a118720f7fe">

---
### 알아보기
1. ECR에 새로운 이미지가 올라오면 CodePipeline을 돌려주는 방법
- 이 방법을 찾는 게 베스트 일것 같습니다 😭 😭 😭 

### 대안
1. GitHub Actions로 latest태그 ECR변경 여부가 아닌 
- GitHub코드 변경 되었을 때 CodePipeline 트리거하기 + CodeBuild(buildspec.yml)를 이용하여 GitHub 코드 변경 시 ECR에 이미지 배포 후 ECS에 Deploy하기

3. GitHub Actions 스크립트에서 ECR 이미지 업로드 + ECS 배포 동시에 하기
- [레퍼런스](https://gcore.com/blog/github-actions-how-to-improve-your-ci-cd-workflow/)

---
- ECS 까지는 아직 확인을 못 해봤습니다 😢  조금 더 시도 해 보겠습니다!

**Comment by stae1102** [comment]
> - 현재 테스트 브랜치로 Push를 하면 깃헙 액션이 돌고 ECR에 latest 태그로 새로 이미지가 생성됩니다.
> - 하지만 latest가 생성 된 후 또 다시 새로 푸시를 latest 태그로 이미지를 올리면 이전의 최신 이미지는 untagged로 변경됩니다.

오 맞아요 저도 다른 서비스에서 사용할 때 이렇게 태그가 변하더라고요!!

**Comment by stae1102** [comment]
> 그렇기에 GitHub Action 스크립트에서 ECR로 태그는 유일한 hash 값으로 주는 것이 아닌 고정을 해 놓아야 합니다.

codePipeline이 감지할 수 있도록 이렇게 하는 게 맞군요 역시 동현님 👍🏻

**Comment by stae1102** [comment]
> GitHub Actions 스크립트에서 ECR 이미지 업로드 + ECS 배포 동시에 하기

뭔가 3번을 통해서 codepipeline이 감지해서 ECS 배포 동시에 할 수 있게 하는 그림이 그려지네요 ㅋㅋ 좋습니다 여러 대안이 있군요

**Comment by stae1102** [comment]
고생하셨습니다 동현님

어제 상준님, 상범님이랑 프론트엔드/백엔드 구글 회원가입 및 로그인 api에 대해서 논의했고 실제 동작하는지 제가 예전에 짜둔 Next.js 소스코드랑 Nest.js 소스코드로 테스트도 해봤습니다! 오늘 저녁에 회식이 있어서 시간이 될지는 모르겠는데 오늘 저녁~내일 점심까지 작업해서 공유할게요!

**Comment by PracticeEveryday** [comment]
> 고생하셨습니다 동현님
> 
> 어제 상준님, 상범님이랑 프론트엔드/백엔드 구글 회원가입 및 로그인 api에 대해서 논의했고 실제 동작하는지 제가 예전에 짜둔 Next.js 소스코드랑 Nest.js 소스코드로 테스트도 해봤습니다! 오늘 저녁에 회식이 있어서 시간이 될지는 모르겠는데 오늘 저녁~내일 점심까지 작업해서 공유할게요!

네네 감사합니다 ㅎㅎㅎ 이 이슈 관련해서 좀 더 찾아보고 디벨로 해보도록 할게요! 
내일 만나서 제일 좋은 방법으로 가져가 보시죠! 😄

**Comment by stae1102** [comment]
동현님 멋져요
