### ISSUE TITLE
[경험 분해] 경험 분해 DB 테이블 셋팅하기

### ISSUE THREAD

**Issue by PracticeEveryday** [depromeet/13th-4team-backend#35]
## 경험분해 DB 테이블 세팅
- 해당 부분 테이블 Prisma ORM Schema Setting하기
<img width="804" alt="image" src="https://github.com/depromeet/13th-4team-backend/assets/97580759/8160f7a8-b42c-4a64-ace6-44cdce5d1914">

**Comment by PracticeEveryday** [comment]
@stae1102  성태님이 해주셨...ㅎㅎㅎㅎㅎ 감사합니다.

**Comment by stae1102** [comment]
지송합니다 ㅎㅎ,,,, 제가 작업하려면 후다닥 해야 해서!
