### ISSUE TITLE
[경험분해] 경험분해 조회 API

### ISSUE THREAD

**Issue by PracticeEveryday** [depromeet/13th-4team-backend#70]
# 경험분해 조회 API Flow 수정

<img width="404" alt="image" src="https://github.com/depromeet/13th-4team-backend/assets/97580759/b7cf17e3-d3ef-4a4f-96a9-625bd0276cad">

- 지금처럼 userId로 조회하는 것이 아닌 유저의 작성 중인 경험 분해 존재 여부( where: Inprogress)에 따라 보내지는 데이터가 달라질 수 있도록 처리하기

**Comment by PracticeEveryday** [comment]
경험분해 조회 API를 user의 id로 조회할 수 있도록 수정했습니다.

**Comment by stae1102** [comment]
넘흐조아여
